name: starwars_app
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  http: ^1.1.0
  flutter_mobx: ^2.2.0+2
  mobx: ^2.3.0+1
  asuka: ^2.2.0
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  mobx_codegen: ^2.6.0+1


flutter:


  uses-material-design: true

  assets:
     - assets/translations/
     - assets/fundo.png
  #   - images/a_dot_ham.jpeg

